### ISSUE TITLE
import deletes `raw/` folder

### ISSUE THREAD

**Issue by jschlatow** [nfeske/goa#16]
I understand that `goa import` supports populating the raw folder. However, this prevents keeping a manually managed raw/ folder in conjunction with the import feature.

**Comment by nfeske** [comment]
Would it be an option to host the manually managed raw content in a separate goa project? I think that the clear-cut distinction between importing content (be it src or raw) from hosted content for each project is beneficial. Otherwise, the same question could be raised about the handling of the src content (which is also deleted for import projects).

**Comment by jschlatow** [comment]
That would be an option.

In any case, I was not aware that the import is allowed to touch raw/ at all as I haven't found any documentation on the conflict/distinction between imported and hosted content. If I hadn't already staged the content, I would have lost the data in raw/. I still think the policy of only deleting src/ and raw/ if it is actually populated by the import (as done in 3c6eeda) is a good compromise as it prevents unexpected data loss.

**Comment by chelmuth** [comment]
I'd very much appreciate if these experiences could be conserved in the documentation by a prominent warning or "do not expect to" section. From my own experience with Goa, it's just a matter of days such imperfections are forgotten despite the value for new users.

**Comment by jschlatow** [comment]
I just pushed 88c24c8, which adds mentioning of the conflict between import and hosted content in src and raw at two places.

**Comment by nfeske** [comment]
Thanks @jschlatow  for both commits, which I have merged to master now.
